name: scmdata CI-CD
on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

jobs:
  linting-and-docs:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dev dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e .[dev]
    # TODO: add `pylint src`
    - name: Formatting and linters
      run: |
        black --check src tests setup.py
        black-nb --check notebooks
        isort --check-only --quiet src tests setup.py
        pydocstyle src
        bandit -c .bandit.yml -r src/scmdata
        flake8 src tests setup.py
    - name: Build docs
      # treat warnings as errors (-W)...
      # ...but not when being nitpicky (-n)
      run: |
          sphinx-build -M html docs/source docs/build -qW
          sphinx-build -M html docs/source docs/build -Eqn -b coverage
          if [[ -s docs/build/html/python.txt ]]
          then
              echo
              echo \"Error: Documentation missing:\"
              echo
              cat docs/build/html/python.txt
              exit 1
          fi

  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install test dependencies
      run: |
        pip install --upgrade --user pip wheel
        pip install -e .[tests,plotting,optional]
    - name: Test with pytest (${{ runner.os }})
      if: ${{ !startsWith(runner.os, 'Windows') }}
      env:
        MIN_COVERAGE: 90
      run: |
          pytest tests -r a --cov=scmdata --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 1
          fi
    - name: Test with pytest (${{ runner.os }})
      if: startsWith(runner.os, 'Windows')
      env:
        MIN_COVERAGE: 90
      run: |
          pytest tests -r a --cov=scmdata --cov-report=term-missing --cov-fail-under=$env:MIN_COVERAGE
    - name: Upload coverage to Codecov
      if: startsWith(runner.os, 'Linux') && matrix.python-version == 3.7
      uses: codecov/codecov-action@v1
      with:
        file: ./coverage.xml

  build-pandas-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]
        pandas-version: [1.0.5, 1.1]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e .[tests,plotting,optional]

          pip install pandas==${{ matrix.pandas-version }}

      - name: Test with pytest
        env:
          MIN_COVERAGE: 90
        run: |
          pytest tests -r a --cov=scmdata --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 1
          fi

  build-xarray-versions:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [ 3.7 ]
        xarray-version: [ 0.16.2, 0.17.0, 0.18.2 ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e .[tests,plotting,optional]

          pip install xarray==${{ matrix.xarray-version }}

      - name: Test with pytest
        env:
          MIN_COVERAGE: 90
        run: |
          pytest tests -r a --cov=scmdata --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 1
          fi

  build-no-plotting:
    # seaborn imports scipy which can make it available without being explicit.
    # This test makes sure that everything works even if the plotting
    # dependencies aren't installed.
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          pip install --upgrade pip wheel
          pip install -e .[tests,optional]

      - name: Test with pytest
        env:
          # drop coverage as not including plotting
          MIN_COVERAGE: 1
        run: |
          pytest tests -r a --cov=scmdata --cov-report=xml --cov-fail-under=${MIN_COVERAGE}
          if ! coverage report --fail-under=${MIN_COVERAGE} --show-missing
          then
              echo
              echo "Error: Test coverage has to be at least ${MIN_COVERAGE}"
              exit 1
          fi

  test-notebooks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install notebook dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e .[tests,notebooks]
    - name: Test notebooks with nbval
      run: |
          pytest notebooks -r a --nbval-lax --sanitize-with tests/notebook-tests.cfg --no-cov
    - name: Test notebooks strictly
      if: matrix.python-version == 3.9
      run: |
        pytest notebooks -r a --nbval --sanitize-with tests/notebook-tests.cfg --no-cov

  test-install:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install
      run: |
        pip install --upgrade pip wheel
        pip install .
    - name: Test installation
      run: |
          python scripts/test_install.py

  deploy-pypi:
    needs: [linting-and-docs,build,build-pandas-versions,build-no-plotting,test-notebooks,test-install]
    if: startsWith(github.ref, 'refs/tags/v')

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
    - name: Setup python
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip wheel
        pip install -e .[dev]
    - name: Create package
      run: python setup.py sdist bdist_wheel --universal
    - name: Publish package to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        user: __token__
        password: ${{ secrets.pypi_password }}
